<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PaisSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('pais')->insert(
            [
				['id'=>1,'nome'=>'NAO INFORMADO','cod_ibge' =>0]
                ,['id'=>2,'nome'=>'AFEGANISTAO','cod_ibge' =>132]
                ,['id'=>3,'nome'=>'AFRICA DO SUL','cod_ibge' =>7560]
                ,['id'=>4,'nome'=>'ALBANIA, REPUBLICA DA','cod_ibge' =>175]
                ,['id'=>5,'nome'=>'ALEMANHA','cod_ibge' =>230]
                ,['id'=>6,'nome'=>'ANDORRA','cod_ibge' =>370]
                ,['id'=>7,'nome'=>'ANGOLA','cod_ibge' =>400]
                ,['id'=>8,'nome'=>'ANGUILLA','cod_ibge' =>418]
                ,['id'=>9,'nome'=>'ANTIGUA E BARBUDA','cod_ibge' =>434]
                ,['id'=>10,'nome'=>'ANTILHAS HOLANDESAS','cod_ibge' =>477]
                ,['id'=>11,'nome'=>'ARABIA SAUDITA','cod_ibge' =>531]
                ,['id'=>12,'nome'=>'ARGELIA','cod_ibge' =>590]
                ,['id'=>13,'nome'=>'ARGENTINA','cod_ibge' =>639]
                ,['id'=>14,'nome'=>'ARMENIA, REPUBLICA DA','cod_ibge' =>647]
                ,['id'=>15,'nome'=>'ARUBA','cod_ibge' =>655]
                ,['id'=>16,'nome'=>'AUSTRALIA','cod_ibge' =>698]
                ,['id'=>17,'nome'=>'AUSTRIA','cod_ibge' =>728]
                ,['id'=>18,'nome'=>'AZERBAIJAO, REPUBLICA DO','cod_ibge' =>736]
                ,['id'=>19,'nome'=>'BAHAMAS, ILHAS','cod_ibge' =>779]
                ,['id'=>20,'nome'=>'BAHREIN, ILHAS','cod_ibge' =>809]
                ,['id'=>21,'nome'=>'BANGLADESH','cod_ibge' =>817]
                ,['id'=>22,'nome'=>'BARBADOS','cod_ibge' =>833]
                ,['id'=>23,'nome'=>'BELARUS, REPUBLICA DA','cod_ibge' =>850]
                ,['id'=>24,'nome'=>'BELGICA','cod_ibge' =>876]
                ,['id'=>25,'nome'=>'BELIZE','cod_ibge' =>884]
                ,['id'=>26,'nome'=>'BENIN','cod_ibge' =>2291]
                ,['id'=>27,'nome'=>'BERMUDAS','cod_ibge' =>906]
                ,['id'=>28,'nome'=>'BOLIVIA','cod_ibge' =>973]
                ,['id'=>29,'nome'=>'BOSNIA-HERZEGOVINA (REPUBLICA DA, 0)','cod_ibge' =>981]
                ,['id'=>30,'nome'=>'BOTSUANA','cod_ibge' =>1015]
                ,['id'=>31,'nome'=>'BRASIL','cod_ibge' =>1058]
                ,['id'=>32,'nome'=>'BRUNEI','cod_ibge' =>1082]
                ,['id'=>33,'nome'=>'BULGARIA, REPUBLICA DA','cod_ibge' =>1112]
                ,['id'=>34,'nome'=>'BURKINA FASO','cod_ibge' =>310]
                ,['id'=>35,'nome'=>'BURUNDI','cod_ibge' =>1155]
                ,['id'=>36,'nome'=>'BUTAO','cod_ibge' =>1198]
                ,['id'=>37,'nome'=>'CABO VERDE, REPUBLICA DE','cod_ibge' =>1279]
                ,['id'=>38,'nome'=>'CAMAROES','cod_ibge' =>1457]
                ,['id'=>39,'nome'=>'CAMBOJA','cod_ibge' =>1414]
                ,['id'=>40,'nome'=>'CANADA','cod_ibge' =>1490]
                ,['id'=>41,'nome'=>'CANARIAS, ILHAS','cod_ibge' =>1511]
                ,['id'=>42,'nome'=>'CATAR','cod_ibge' =>1546]
                ,['id'=>43,'nome'=>'CAYMAN, ILHAS','cod_ibge' =>1376]
                ,['id'=>44,'nome'=>'CAZAQUISTAO, REPUBLICA DO','cod_ibge' =>1538]
                ,['id'=>45,'nome'=>'CHADE','cod_ibge' =>7889]
                ,['id'=>46,'nome'=>'CHILE','cod_ibge' =>1589]
                ,['id'=>47,'nome'=>'CHINA, REPUBLICA POPULAR','cod_ibge' =>1600]
                ,['id'=>48,'nome'=>'CHIPRE','cod_ibge' =>1635]
                ,['id'=>49,'nome'=>'CHRISTMAS,ILHA (NAVIDAD, 0)','cod_ibge' =>5118]
                ,['id'=>50,'nome'=>'CINGAPURA','cod_ibge' =>7412]
                ,['id'=>51,'nome'=>'COCOS(KEELING, 0),ILHAS','cod_ibge' =>1651]
                ,['id'=>52,'nome'=>'COLOMBIA','cod_ibge' =>1694]
                ,['id'=>53,'nome'=>'COMORES, ILHAS','cod_ibge' =>1732]
                ,['id'=>54,'nome'=>'CONGO','cod_ibge' =>1775]
                ,['id'=>55,'nome'=>'CONGO, REPUBLICA DEMOCRATICA DO','cod_ibge' =>8885]
                ,['id'=>56,'nome'=>'COOK, ILHAS','cod_ibge' =>1830]
                ,['id'=>57,'nome'=>'COREIA, REP.POP.DEMOCRATICA','cod_ibge' =>1872]
                ,['id'=>58,'nome'=>'COREIA, REPUBLICA DA','cod_ibge' =>1902]
                ,['id'=>59,'nome'=>'COSTA DO MARFIM','cod_ibge' =>1937]
                ,['id'=>60,'nome'=>'COSTA RICA','cod_ibge' =>1961]
                ,['id'=>61,'nome'=>'COVEITE','cod_ibge' =>1988]
                ,['id'=>62,'nome'=>'CROACIA (REPUBLICA DA, 0)','cod_ibge' =>1953]
                ,['id'=>63,'nome'=>'CUBA','cod_ibge' =>1996]
                ,['id'=>64,'nome'=>'DINAMARCA','cod_ibge' =>2321]
                ,['id'=>65,'nome'=>'DJIBUTI','cod_ibge' =>7838]
                ,['id'=>66,'nome'=>'DOMINICA,ILHA','cod_ibge' =>2356]
                ,['id'=>67,'nome'=>'EGITO','cod_ibge' =>2402]
                ,['id'=>68,'nome'=>'EL SALVADOR','cod_ibge' =>6874]
                ,['id'=>69,'nome'=>'EMIRADOS ARABES UNIDOS','cod_ibge' =>2445]
                ,['id'=>70,'nome'=>'EQUADOR','cod_ibge' =>2399]
                ,['id'=>71,'nome'=>'ERITREIA','cod_ibge' =>2437]
                ,['id'=>72,'nome'=>'ESLOVACA, REPUBLICA','cod_ibge' =>2470]
                ,['id'=>73,'nome'=>'ESLOVENIA, REPUBLICA DA','cod_ibge' =>2461]
                ,['id'=>74,'nome'=>'ESPANHA','cod_ibge' =>2453]
                ,['id'=>75,'nome'=>'ESTADOS UNIDOS','cod_ibge' =>2496]
                ,['id'=>76,'nome'=>'ESTONIA, REPUBLICA DA','cod_ibge' =>2518]
                ,['id'=>77,'nome'=>'ETIOPIA','cod_ibge' =>2534]
                ,['id'=>78,'nome'=>'FALKLAND (ILHAS MALVINAS, 0)','cod_ibge' =>2550]
                ,['id'=>79,'nome'=>'FEROE, ILHAS','cod_ibge' =>2593]
                ,['id'=>80,'nome'=>'FIJI','cod_ibge' =>8702]
                ,['id'=>81,'nome'=>'FILIPINAS','cod_ibge' =>2674]
                ,['id'=>82,'nome'=>'FINLANDIA','cod_ibge' =>2712]
                ,['id'=>83,'nome'=>'FORMOSA (TAIWAN, 0)','cod_ibge' =>1619]
                ,['id'=>84,'nome'=>'FRANCA','cod_ibge' =>2755]
                ,['id'=>85,'nome'=>'GABAO','cod_ibge' =>2810]
                ,['id'=>86,'nome'=>'GAMBIA','cod_ibge' =>2852]
                ,['id'=>87,'nome'=>'GANA','cod_ibge' =>2895]
                ,['id'=>88,'nome'=>'GEORGIA, REPUBLICA DA','cod_ibge' =>2917]
                ,['id'=>89,'nome'=>'GIBRALTAR','cod_ibge' =>2933]
                ,['id'=>90,'nome'=>'GRANADA','cod_ibge' =>2976]
                ,['id'=>91,'nome'=>'GRECIA','cod_ibge' =>3018]
                ,['id'=>92,'nome'=>'GROENLANDIA','cod_ibge' =>3050]
                ,['id'=>93,'nome'=>'GUADALUPE','cod_ibge' =>3093]
                ,['id'=>94,'nome'=>'GUAM','cod_ibge' =>3131]
                ,['id'=>95,'nome'=>'GUATEMALA','cod_ibge' =>3174]
                ,['id'=>96,'nome'=>'GUERNSEY, ILHA DO CANAL (INCLUI ALDERNEY E SARK, 0)','cod_ibge' =>1504]
                ,['id'=>97,'nome'=>'GUIANA','cod_ibge' =>3379]
                ,['id'=>98,'nome'=>'GUIANA FRANCESA','cod_ibge' =>3255]
                ,['id'=>99,'nome'=>'GUINE','cod_ibge' =>3298]
                ,['id'=>100,'nome'=>'GUINE-BISSAU','cod_ibge' =>3344]
                ,['id'=>101,'nome'=>'GUINE-EQUATORIAL','cod_ibge' =>3310]
                ,['id'=>102,'nome'=>'HAITI','cod_ibge' =>3417]
                ,['id'=>103,'nome'=>'HONDURAS','cod_ibge' =>3450]
                ,['id'=>104,'nome'=>'HONG KONG','cod_ibge' =>3514]
                ,['id'=>105,'nome'=>'HUNGRIA, REPUBLICA DA','cod_ibge' =>3557]
                ,['id'=>106,'nome'=>'IEMEN','cod_ibge' =>3573]
                ,['id'=>107,'nome'=>'INDIA','cod_ibge' =>3611]
                ,['id'=>108,'nome'=>'INDONESIA','cod_ibge' =>3654]
                ,['id'=>109,'nome'=>'IRA, REPUBLICA ISLAMICA DO','cod_ibge' =>3727]
                ,['id'=>110,'nome'=>'IRAQUE','cod_ibge' =>3697]
                ,['id'=>111,'nome'=>'IRLANDA','cod_ibge' =>3751]
                ,['id'=>112,'nome'=>'ISLANDIA','cod_ibge' =>3794]
                ,['id'=>113,'nome'=>'ISRAEL','cod_ibge' =>3832]
                ,['id'=>114,'nome'=>'ITALIA','cod_ibge' =>3867]
                ,['id'=>115,'nome'=>'JAMAICA','cod_ibge' =>3913]
                ,['id'=>116,'nome'=>'JAPAO','cod_ibge' =>3999]
                ,['id'=>117,'nome'=>'JERSEY, ILHA DO CANAL','cod_ibge' =>1508]
                ,['id'=>118,'nome'=>'JOHNSTON, ILHAS','cod_ibge' =>3964]
                ,['id'=>119,'nome'=>'JORDANIA','cod_ibge' =>4030]
                ,['id'=>120,'nome'=>'KIRIBATI','cod_ibge' =>4111]
                ,['id'=>121,'nome'=>'LAOS, REP.POP.DEMOCR.DO','cod_ibge' =>4200]
                ,['id'=>122,'nome'=>'LEBUAN,ILHAS','cod_ibge' =>4235]
                ,['id'=>123,'nome'=>'LESOTO','cod_ibge' =>4260]
                ,['id'=>124,'nome'=>'LETONIA, REPUBLICA DA','cod_ibge' =>4278]
                ,['id'=>125,'nome'=>'LIBANO','cod_ibge' =>4316]
                ,['id'=>126,'nome'=>'LIBERIA','cod_ibge' =>4340]
                ,['id'=>127,'nome'=>'LIBIA','cod_ibge' =>4383]
                ,['id'=>128,'nome'=>'LIECHTENSTEIN','cod_ibge' =>4405]
                ,['id'=>129,'nome'=>'LITUANIA, REPUBLICA DA','cod_ibge' =>4421]
                ,['id'=>130,'nome'=>'LUXEMBURGO','cod_ibge' =>4456]
                ,['id'=>131,'nome'=>'MACAU','cod_ibge' =>4472]
                ,['id'=>132,'nome'=>'MACEDONIA, ANT.REP.IUGOSLAVA','cod_ibge' =>4499]
                ,['id'=>133,'nome'=>'MADAGASCAR','cod_ibge' =>4502]
                ,['id'=>134,'nome'=>'MADEIRA, ILHA DA','cod_ibge' =>4525]
                ,['id'=>135,'nome'=>'MALASIA','cod_ibge' =>4553]
                ,['id'=>136,'nome'=>'MALAVI','cod_ibge' =>4588]
                ,['id'=>137,'nome'=>'MALDIVAS','cod_ibge' =>4618]
                ,['id'=>138,'nome'=>'MALI','cod_ibge' =>4642]
                ,['id'=>139,'nome'=>'MALTA','cod_ibge' =>4677]
                ,['id'=>140,'nome'=>'MAN, ILHA DE','cod_ibge' =>3595]
                ,['id'=>141,'nome'=>'MARIANAS DO NORTE','cod_ibge' =>4723]
                ,['id'=>142,'nome'=>'MARROCOS','cod_ibge' =>4740]
                ,['id'=>143,'nome'=>'MARSHALL,ILHAS','cod_ibge' =>4766]
                ,['id'=>144,'nome'=>'MARTINICA','cod_ibge' =>4774]
                ,['id'=>145,'nome'=>'MAURICIO','cod_ibge' =>4855]
                ,['id'=>146,'nome'=>'MAURITANIA','cod_ibge' =>4880]
                ,['id'=>147,'nome'=>'MEXICO','cod_ibge' =>4936]
                ,['id'=>148,'nome'=>'MIANMAR (BIRMANIA, 0)','cod_ibge' =>930]
                ,['id'=>149,'nome'=>'MICRONESIA','cod_ibge' =>4995]
                ,['id'=>150,'nome'=>'MIDWAY, ILHAS','cod_ibge' =>4901]
                ,['id'=>151,'nome'=>'MOCAMBIQUE','cod_ibge' =>5053]
                ,['id'=>152,'nome'=>'MOLDAVIA, REPUBLICA DA','cod_ibge' =>4944]
                ,['id'=>153,'nome'=>'MONACO','cod_ibge' =>4952]
                ,['id'=>154,'nome'=>'MONGOLIA','cod_ibge' =>4979]
                ,['id'=>155,'nome'=>'MONTENEGRO','cod_ibge' =>4985]
                ,['id'=>156,'nome'=>'MONTSERRAT,ILHAS','cod_ibge' =>5010]
                ,['id'=>157,'nome'=>'NAMIBIA','cod_ibge' =>5070]
                ,['id'=>158,'nome'=>'NAURU','cod_ibge' =>5088]
                ,['id'=>159,'nome'=>'NEPAL','cod_ibge' =>5177]
                ,['id'=>160,'nome'=>'NICARAGUA','cod_ibge' =>5215]
                ,['id'=>161,'nome'=>'NIGER','cod_ibge' =>5258]
                ,['id'=>162,'nome'=>'NIGERIA','cod_ibge' =>5282]
                ,['id'=>163,'nome'=>'NIUE,ILHA','cod_ibge' =>5312]
                ,['id'=>164,'nome'=>'NORFOLK,ILHA','cod_ibge' =>5355]
                ,['id'=>165,'nome'=>'NORUEGA','cod_ibge' =>5380]
                ,['id'=>166,'nome'=>'NOVA CALEDONIA','cod_ibge' =>5428]
                ,['id'=>167,'nome'=>'NOVA ZELANDIA','cod_ibge' =>5487]
                ,['id'=>168,'nome'=>'OMA','cod_ibge' =>5568]
                ,['id'=>169,'nome'=>'PACIFICO,ILHAS DO (POSSESSAO DOS EUA, 0)','cod_ibge' =>5665]
                ,['id'=>170,'nome'=>'pais BAIXOS (HOLANDA, 0)','cod_ibge' =>5738]
                ,['id'=>171,'nome'=>'PALAU','cod_ibge' =>5754]
                ,['id'=>172,'nome'=>'PANAMA','cod_ibge' =>5800]
                ,['id'=>173,'nome'=>'PAPUA NOVA GUINE','cod_ibge' =>5452]
                ,['id'=>174,'nome'=>'PAQUISTAO','cod_ibge' =>5762]
                ,['id'=>175,'nome'=>'PARAGUAI','cod_ibge' =>5860]
                ,['id'=>176,'nome'=>'PERU','cod_ibge' =>5894]
                ,['id'=>177,'nome'=>'PITCAIRN,ILHA','cod_ibge' =>5932]
                ,['id'=>178,'nome'=>'POLINESIA FRANCESA','cod_ibge' =>5991]
                ,['id'=>179,'nome'=>'POLONIA, REPUBLICA DA','cod_ibge' =>6033]
                ,['id'=>180,'nome'=>'PORTO RICO','cod_ibge' =>6114]
                ,['id'=>181,'nome'=>'PORTUGAL','cod_ibge' =>6076]
                ,['id'=>182,'nome'=>'QUENIA','cod_ibge' =>6238]
                ,['id'=>183,'nome'=>'QUIRGUIZ, REPUBLICA','cod_ibge' =>6254]
                ,['id'=>184,'nome'=>'REINO UNIDO','cod_ibge' =>6289]
                ,['id'=>185,'nome'=>'REPUBLICA CENTRO-AFRICANA','cod_ibge' =>6408]
                ,['id'=>186,'nome'=>'REPUBLICA DOMINICANA','cod_ibge' =>6475]
                ,['id'=>187,'nome'=>'REUNIAO, ILHA','cod_ibge' =>6602]
                ,['id'=>188,'nome'=>'ROMENIA','cod_ibge' =>6700]
                ,['id'=>189,'nome'=>'RUANDA','cod_ibge' =>6750]
                ,['id'=>190,'nome'=>'RUSSIA, FEDERACAO DA','cod_ibge' =>6769]
                ,['id'=>191,'nome'=>'SAARA OCIDENTAL','cod_ibge' =>6858]
                ,['id'=>192,'nome'=>'SAINT KITTS E NEVIS','cod_ibge' =>6781]
                ,['id'=>193,'nome'=>'SALOMAO, ILHAS','cod_ibge' =>6777]
                ,['id'=>194,'nome'=>'SAMOA','cod_ibge' =>6904]
                ,['id'=>195,'nome'=>'SAMOA AMERICANA','cod_ibge' =>6912]
                ,['id'=>196,'nome'=>'SAN MARINO','cod_ibge' =>6971]
                ,['id'=>197,'nome'=>'SANTA HELENA','cod_ibge' =>7102]
                ,['id'=>198,'nome'=>'SANTA LUCIA','cod_ibge' =>7153]
                ,['id'=>199,'nome'=>'SAO CRISTOVAO E NEVES,ILHAS','cod_ibge' =>6955]
                ,['id'=>200,'nome'=>'SAO PEDRO E MIQUELON','cod_ibge' =>7005]
                ,['id'=>201,'nome'=>'SAO VICENTE E GRANADINAS','cod_ibge' =>7056]
                ,['id'=>202,'nome'=>'SENEGAL','cod_ibge' =>7285]
                ,['id'=>203,'nome'=>'SERRA LEOA','cod_ibge' =>7358]
                ,['id'=>204,'nome'=>'SERVIA','cod_ibge' =>7370]
                ,['id'=>205,'nome'=>'SEYCHELLES','cod_ibge' =>7315]
                ,['id'=>206,'nome'=>'SIRIA, REPUBLICA ARABE DA','cod_ibge' =>7447]
                ,['id'=>207,'nome'=>'SOMALIA','cod_ibge' =>7480]
                ,['id'=>208,'nome'=>'SRI LANKA','cod_ibge' =>7501]
                ,['id'=>209,'nome'=>'SUAZILANDIA','cod_ibge' =>7544]
                ,['id'=>210,'nome'=>'SUDAO','cod_ibge' =>7595]
                ,['id'=>211,'nome'=>'SUECIA','cod_ibge' =>7641]
                ,['id'=>212,'nome'=>'SUICA','cod_ibge' =>7676]
                ,['id'=>213,'nome'=>'SURINAME','cod_ibge' =>7706]
                ,['id'=>214,'nome'=>'TADJIQUISTAO, REPUBLICA DO','cod_ibge' =>7722]
                ,['id'=>215,'nome'=>'TAILANDIA','cod_ibge' =>7765]
                ,['id'=>216,'nome'=>'TANZANIA, REP.UNIDA DA','cod_ibge' =>7803]
                ,['id'=>217,'nome'=>'TCHECA, REPUBLICA','cod_ibge' =>7919]
                ,['id'=>218,'nome'=>'TERRITORIO BRIT.OC.INDICO','cod_ibge' =>7820]
                ,['id'=>219,'nome'=>'TIMOR LESTE','cod_ibge' =>7951]
                ,['id'=>220,'nome'=>'TOGO','cod_ibge' =>8001]
                ,['id'=>221,'nome'=>'TONGA','cod_ibge' =>8109]
                ,['id'=>222,'nome'=>'TOQUELAU,ILHAS','cod_ibge' =>8052]
                ,['id'=>223,'nome'=>'TRINIDAD E TOBAGO','cod_ibge' =>8150]
                ,['id'=>224,'nome'=>'TUNISIA','cod_ibge' =>8206]
                ,['id'=>225,'nome'=>'TURCAS E CAICOS,ILHAS','cod_ibge' =>8230]
                ,['id'=>226,'nome'=>'TURCOMENISTAO, REPUBLICA DO','cod_ibge' =>8249]
                ,['id'=>227,'nome'=>'TURQUIA','cod_ibge' =>8273]
                ,['id'=>228,'nome'=>'TUVALU','cod_ibge' =>8281]
                ,['id'=>229,'nome'=>'UCRANIA','cod_ibge' =>8311]
                ,['id'=>230,'nome'=>'UGANDA','cod_ibge' =>8338]
                ,['id'=>231,'nome'=>'URUGUAI','cod_ibge' =>8451]
                ,['id'=>232,'nome'=>'UZBEQUISTAO, REPUBLICA DO','cod_ibge' =>8478]
                ,['id'=>233,'nome'=>'VANUATU','cod_ibge' =>5517]
                ,['id'=>234,'nome'=>'VATICANO, EST.DA CIDADE DO','cod_ibge' =>8486]
                ,['id'=>235,'nome'=>'VENEZUELA','cod_ibge' =>8508]
                ,['id'=>236,'nome'=>'VIETNA','cod_ibge' =>8583]
                ,['id'=>237,'nome'=>'VIRGENS,ILHAS (BRITANICAS, 0)','cod_ibge' =>8630]
                ,['id'=>238,'nome'=>'VIRGENS,ILHAS (E.U.A., 0)','cod_ibge' =>8664]
                ,['id'=>239,'nome'=>'WAKE, ILHA','cod_ibge' =>8737]
                ,['id'=>240,'nome'=>'ZAMBIA','cod_ibge' =>8907]
                ,['id'=>241,'nome'=>'ZIMBABUE','cod_ibge' =>6653],
            ]
        );
    }
}
